source 'https://rubygems.org'

gem 'sinatra-activerecord'
gem 'sqlite3'
gem 'rake'
gem 'sinatra-contrib'
gem 'whenever'
gem 'faraday'
gem 'bcrypt'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'i18n'
gem 'unicorn'
gem 'sentimental'
gem 'whenever', require: false
